"""empty message

Revision ID: 0c9ae255e8db
Revises: e0e1f9debf7f
Create Date: 2021-08-25 18:15:33.827517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9ae255e8db'
down_revision = 'e0e1f9debf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collections', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    # ### end Alembic commands ###
